### ISSUE TITLE
On ajoute liens fedi en data possible optionelle?

### ISSUE THREAD

**Issue by Arteneko** [Arteneko/cypherweavers.cafe#1]
Ça ferait un lien rel=me sur le bloc de notre site du ring quoi

**Comment by nononymousse** [comment]
owi grave ^^

**Comment by Arteneko** [comment]
![image](https://user-images.githubusercontent.com/23583792/232468165-6d539a30-bedd-4c60-ae4a-e22521140f46.png)
j'ai bricolé ça aussi du coup qui l'intègre, vous en pensez quoi ? (pas certaine pour le décor du badge, mais still, pas trop d'idée autre pour ça

**Comment by nononymousse** [comment]
OwO love it, ça fait des petites tab d'un dossier j'aime bien ^^

**Comment by Arteneko** [comment]
![image](https://user-images.githubusercontent.com/23583792/232480732-b5b6552c-fcd3-41f0-a529-cde4c7edd2a6.png)

**Comment by nononymousse** [comment]
je préferait l'ancienne version en vrai, ça faisait moins abrupte je trouve

**Comment by Arteneko** [comment]
Ok, jle ferai apres le taff
Hesitez pas a jouer ac le css aussi btw

**Comment by nononymousse** [comment]
J'ai tenter un petit truc
(voulait essayer de rajouter un coin à 45° en haut à gauche du badge mais pas réussis)
![image](https://user-images.githubusercontent.com/32956707/232502963-07ffe17e-2ec2-4741-875b-5045b2a6cc90.png)
